config/routes.rb
Rails.application.routes.draw do
  resources :coupons, only: [ :index, :new, :create, :destroy ] do
    member do
      patch :toggle_status
    end
  end
  resources :busines, only: [ :index, :new, :create, :show, :destroy ]
  resources :dashboards, only: [ :index ]
  resources :verify_mobile_no, only: [ :new, :create ]
  resources :help, only: [ :index ]
  get "profile", to: "users#show", as: :profile
  devise_for :users, controllers: { registrations: "users/registrations" }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/busine.rb
class Busine < ApplicationRecord
  belongs_to :user
  has_many :coupon
  enum :valid_check_status, [ :not_validated, :validating, :valid_gstin, :validation_failed ]
  # Validations
  validates :gstin, presence: true, format: { with: /\A\d{2}[A-Z]{5}\d{4}[A-Z]{1}\d{1}[Z]{1}[A-Z\d]{1}\z/, message: "is not a valid GSTIN format" }

  scope :validated, -> { where(valid_check_status: :valid_gstin) }
end

app/controllers/busines_controller.rb
class BusinesController < ApplicationController
  before_action :set_busine, only: %i[ show edit update destroy ]

  # GET /busines or /busines.json
  def index
    @busines = current_user.busine
  end

  # GET /busines/1 or /busines/1.json
  def show
    @config_obj_1 = [
                    "gstin"
                    ]
    @config_obj_2 = [
                    "valid_check_status"
                    ]
    if @busine.valid_check_status == "valid_gstin"
      @config_obj_1 = [
                        "gstin",
                        "trade_name",
                        "legal_name",
                        "constitution",
                        "status",
                        "registration_date",
                        "last_update",
                        "taxpayer_type", "nature_of_business", "principal_nature_of_business", "filing_frequency",
                        "cancellation_date"
                        ]

        @config_obj_2 = [
                        "valid_check_status", "state_jurisdiction", "state_jurisdiction_code",
                        "center_jurisdiction", "center_jurisdiction_code",
                        "building_number",
                        "building_name", "street", "location", "district", "state_code", "pin_code",
                        "latitude", "longitude"
                        ]
    end
  end

  # GET /busines/new
  def new
    @busine = Busine.new
  end

  # GET /busines/1/edit
  def edit
  end

  # POST /busines or /busines.json
  def create
    @busine = Busine.new(busine_params)
    @busine.user_id = current_user.id

    respond_to do |format|
      if @busine.save
        format.html { redirect_to @busine, notice: "Busine was successfully created." }
        format.json { render :show, status: :created, location: @busine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @busine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /busines/1 or /busines/1.json
  def update
    respond_to do |format|
      if @busine.update(busine_params)
        format.html { redirect_to @busine, notice: "Busine was successfully updated." }
        format.json { render :show, status: :ok, location: @busine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @busine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busines/1 or /busines/1.json
  def destroy
    @busine.destroy!

    respond_to do |format|
      format.html { redirect_to busines_path, status: :see_other, notice: "Busine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busine
      @busine = Busine.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def verify_mobile_no_params
      params.require(:busine).permit(:gstin)
    end
end

app/helpers/busines_helper.rb
module BusinesHelper
end

app/views/busines/_form.html.erb
<div class="flex items-center justify-center">
  <div class="w-full max-w-md p-6 bg-white rounded-xl shadow-md">
<%= form_with(model: busine, class: "contents", html: {class: "space-y-4" }) do |f| %>
  <% if busine.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(busine.errors.count, "error") %> prohibited this busines from being saved:</h2>

      <ul class="list-disc ml-6">
        <% busine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
      <%= f.label "GSTIN", class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :gstin, :maxlength => 15,  autofocus: true, autocomplete: "gstin", class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
    </div>

  <div>
    <%= f.submit "Add New Business", class: "w-full bg-sky-500 hover:bg-sky-700 text-white font-medium py-2 px-4 rounded-lg transition" %>
  </div>
<% end %>
  </div>
</div>

app/views/busines/index.html.erb
  <%= render "layouts/top", content_title: "Business", title: "Business", button_text: "Add New Business", button_path: new_busine_path%>

  <div id="busines" class="min-w-full">
    <% if @busines.any? %>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    GSTIN
                </th>
                <th scope="col" class="px-6 py-3">
                    Status
                </th>
                <th scope="col" class="px-6 py-3">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
          <% @busines.each do |busine| %>
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 border-gray-200">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    <%= busine.gstin %>
                </th>
                <td class="px-6 py-4">
                    <span class="py-2 px-3
                      <%= case busine.valid_check_status
                          when 'not_validated' then 'bg-gray-800'
                          when 'validating' then 'bg-blue-400'
                          when 'valid_gstin' then 'bg-green-500'
                          when 'validation_failed' then 'bg-red-500'
                          end %> text-white font-medium rounded-md inline-block">
                      <%= busine.valid_check_status.humanize %>
                    </span>
                </td>
                <td class="px-6 py-4">
                    <%= link_to "Show", busine_path(busine.id), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
            </tr>
          <% end %>
        </tbody>

    </table>
    </div>
    <% else %>
      <p class="text-center my-10 dark:text-white">No busines found.</p>
    <% end %>
  </div>

app/views/busines/new.html.erb
<% content_for :title, "New busine" %>
  <div class="flex justify-between items-center mb-6">
    <h2 class="text-4xl font-extrabold dark:text-white">New Busines</h2>
    <%= link_to "Back to busines", busines_path, class: "text-center hover:bg-sky-700 text-white font-medium py-2 px-4 rounded-lg transition" %>
  </div>
  <%= render "form", busine: @busine %>

app/views/busines/show.html.erb
<%= render "layouts/top", content_title: "Showing Busines", title: @busine.trade_name, button_text: "Back To Business", button_path: busines_path%>

<div class="flex justify-between bg-white rounded-xl shadow-md">
  <div class="w-full p-6 ">
          <% @config_obj_1.each do |key| %>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                <%= key.humanize %>
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= @busine[key] %>
              </dd>
            </div>
          <% end %>
  </div>
    <div class="w-full p-6">
          <% @config_obj_2.each do |key| %>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                <%= key.humanize %>
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                <%= @busine[key].try(:humanize) %>
              </dd>
            </div>
          <% end %>
  </div>
</div>
<div class="flex justify-end items-center">
  <%= button_to "Remove this busine", @busine, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
</div>