config/routes.rb
Rails.application.routes.draw do
  resources :coupons, only: [ :index, :new, :create, :destroy ] do
    member do
      patch :toggle_status
    end
  end
  resources :busines, only: [ :index, :new, :create, :show, :destroy ]
  resources :dashboards, only: [ :index ]
  resources :verify_mobile_no, only: [ :new, :create ]
  resources :help, only: [ :index ]
  get "profile", to: "users#show", as: :profile
  devise_for :users, controllers: { registrations: "users/registrations" }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/controllers/verify_mobile_no_controller.rb
class VerifyMobileNoController < ApplicationController
  def new
    redirect_to profile_path, notice: "no mobile no added!" if current_user.mobile_no.empty?
    if current_user.mobile_no_verified
      redirect_to profile_path, notice: "OTP Already Verified"
    end
    send_otp
  end

  def create
    if current_user.verify_otp(verify_mobile_no_params[:otp])
      redirect_to profile_path, notice: "OTP verfied!"
    else
      redirect_to profile_path, notice: "Wrong OTP entered!"
    end
  end

  private

  def verify_mobile_no_params
    params.permit(:otp, :authenticity_token, :commit)
  end

  def send_otp
    if current_user.otp_valid?
      flash.now[:notice] = "Valid otp already sent"
    else
      current_user.generate_otp
      current_user.send_otp_to_user
      flash.now[:notice] = "OTP sent!"
    end
  end
end

app/helpers/verify_mobile_no_helper.rb
module VerifyMobileNoHelper
end

app/views/verify_mobile_no/new.html.erb
<% content_for :title, "Verify Mobile No" %>
<div class="flex justify-between items-center mb-6">
  <h2 class="text-4xl font-extrabold dark:text-white">Verify Mobile No</h2>
  <%= link_to "Back to Profile", profile_path, class: "text-center hover:bg-sky-700 text-white font-medium py-2 px-4 rounded-lg transition" %>
</div>

<div class="flex items-center justify-center">
  <div class="w-full max-w-md p-6 bg-white rounded-xl shadow-md">
<%= form_with(url: verify_mobile_no_index_path, class: "contents", html: {class: "space-y-4" }) do |f| %>
    <div>
      <%= f.text_field :otp, :placeholder => "Enter OTP here", :maxlength => 6,  autofocus: true, autocomplete: "gstin", class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
    </div>

    <div>
      <%= f.submit "Submit OTP", class: " cursor-pointer w-full bg-sky-500 hover:bg-sky-700 text-white font-medium py-2 px-4 rounded-lg transition" %>
    </div>
<% end %>
  </div>
</div>