config/routes.rb
Rails.application.routes.draw do
  resources :coupons, only: [ :index, :new, :create, :destroy ] do
    member do
      patch :toggle_status
    end
  end
  resources :busines, only: [ :index, :new, :create, :show, :destroy ]
  resources :dashboards, only: [ :index ]
  resources :verify_mobile_no, only: [ :new, :create ]
  resources :help, only: [ :index ]
  get "profile", to: "users#show", as: :profile
  devise_for :users, controllers: { registrations: "users/registrations" }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :user
  belongs_to :busine

  enum :coupon_type, [ :falt, :percent_off ]
  validates :code, presence: true, length: { is: 15 }, uniqueness: true

  before_validation :generate_unique_coupon_code, on: :create

  private

  def generate_unique_coupon_code
    return if code.present?  # Avoid overwriting existing code

    loop do
      self.code = SecureRandom.alphanumeric(15).upcase
      break unless Coupon.exists?(code: code)
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: %i[ show edit update destroy ]

  # GET /coupons or /coupons.json
  def index
    @coupons = current_user.coupon
  end

  # GET /coupons/1 or /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
    @businesses = current_user.busine.validated
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons or /coupons.json
  def create
    @quantity = params[:coupon][:quantity].to_i
    @quantity = 1 if @quantity.zero? # Default to 1 if quantity is nil or 0

    @coupons = []
    @quantity.times do
      @coupon = Coupon.new(coupon_params)
      @coupon.user = current_user
      @coupons << @coupon if @coupon.save
    end

    if @coupons.any?
      redirect_to coupons_path, notice: "#{@coupons.count} coupon(s) were successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /coupons/1 or /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: "Coupon was successfully updated." }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1 or /coupons/1.json
  def destroy
    @coupon.destroy!

    respond_to do |format|
      format.html { redirect_to coupons_path, status: :see_other, notice: "Coupon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @coupon = Coupon.find(params[:id])
    @coupon.update(active_status: !@coupon.active_status)

    respond_to do |format|
      format.json { render json: { success: true, active_status: @coupon.active_status } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def coupon_params
      params.require(:coupon).permit(:busine_id, :coupon_type, :value, :valid_up_to)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_coupon.html.erb
<div class="isolated_bs relative max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
    <!-- Triangle Badge -->
  <% if coupon.redeemed %>
  <div class="ribbon ribbon-top-left z-10">
    <span class="text-white font-medium bg-secondary"> Redmed</span>
  </div>
  <% end %>

  <div class="relative mb-2">
        <!-- Coupon Code (Masked by Default) -->
        <span class="text-sm font-bold tracking-tight text-gray-900 dark:text-white code" data-code="<%= coupon.code %>">
            ***************
        </span>
        
        <!-- Toggle Button -->
        <button type="button" class="toggle_coupon_code text-lg font-bold tracking-tight text-gray-900 dark:text-white focus:outline-none">
            Show Code
        </button>
  </div>

  <!-- Coupon Details -->
  <dl>
    <div class="row">
      <dt class="text-sm font-medium text-gray-500 col">Business</dt>
      <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 col-span-2 col">
        <%= coupon.busine.trade_name %>
      </dd>
    </div>

    <div class="row">
        <dt class="text-sm font-medium text-gray-500 col">Valid upto</dt>
        <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 col-span-2 col">
          <%= coupon.valid_up_to.strftime("%d %b %Y %H:%M") if coupon.valid_up_to %>
        </dd>
    </div>

    <div class="row">
        <dt class="text-sm font-medium text-gray-500 col">Type</dt>
        <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 col-span-2 capitalize col">
          <%= coupon.coupon_type.humanize %>
        </dd>

        <dt class="text-sm font-medium text-gray-500 col">Value</dt>
        <dd class="mt-1 text-sm text-gray-900 dark:text-white sm:mt-0 col-span-2 capitalize col">
          <%= coupon.value %>
        </dd>
    </div>

  </dl>


  <!-- Delete Button -->
  <div class="row mt-4">
    <div class="col-4">
      <%= button_to "Delete", coupon_path(coupon), method: :delete, data: { confirm: "Are you sure you want to delete this coupon?" }, class: "p-1 text-sm font-medium text-white bg-red-600 rounded hover:bg-red-700" %>
    </div>
    <div class="form-switch col flex justify-between">
      <label class="text-sm font-medium text-gray-500" for="toggle_coupon_active_status-<%= coupon.id %>">Status</label>
      <input class="form-check-input cursor-pointer toggle_coupon_active_status bg-<%= coupon.active_status ? "success" : "secondary" %>"
            type="checkbox"
            role="switch"
            id="toggle_coupon_active_status-<%= coupon.id %>"
            data-coupon-id="<%= coupon.id %>"
            <%= coupon.active_status ? "checked" : nil %>>
    </div>
  </div>
</div>

app/views/coupons/_form.html.erb
<div class="flex items-center justify-center">
  <div class="w-full max-w-md p-6 bg-white rounded-xl shadow-md">
<%= form_with(model: coupon, class: "contents", html: {class: "space-y-4" }) do |f| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(busine.errors.count, "error") %> prohibited this coupon from being created:</h2>

      <ul class="list-disc ml-6">
        <% coupon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :busine_id, "Select Business", class: "block text-sm font-medium text-gray-700" %>
    <%= f.collection_select :busine_id, businesses, :id, :trade_name, { prompt: "Choose a Business" }, class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
  </div>

  <div>
    <%= f.label :coupon_type, "Type", class: "block text-sm font-medium text-gray-700" %>
    <%= f.select :coupon_type, Coupon.coupon_types.keys.map { |type| [type.humanize, type] }, { prompt: "Choose a Coupon Type" }, class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
  </div>

  <div>
    <%= f.label :type, "Value", class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :value, required: true, class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
  </div>

  <div>
    <%= f.label :type, "Quantity", class: "block text-sm font-medium text-gray-700" %>
    <%= f.text_field :quantity, required: true, class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
  </div>

  <div>
    <%= f.label :valid_up_to, "Valid Up To", class: "block text-sm font-medium text-gray-700" %>
    <%= f.datetime_local_field :valid_up_to, required: true, class: "w-full mt-1 p-2 border border-gray-300 rounded-lg focus:ring-sky-500 focus:border-sky-500" %>
  </div>


  <div>
    <%= f.submit "Create New Coupon", class: "w-full bg-sky-500 cursor-pointer hover:bg-sky-700 text-white font-medium py-2 px-4 rounded-lg transition" %>
  </div>
<% end %>
  </div>
</div>

app/views/coupons/edit.html.erb
<% content_for :title, "Editing coupon" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing coupon</h1>

  <%= render "form", coupon: @coupon %>

  <%= link_to "Show this coupon", @coupon, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to coupons", coupons_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/coupons/index.html.erb
<%= render "layouts/top", content_title: "Coupons", title: "Coupons", button_text: "Create New Coupon", button_path: new_coupon_path%>
<div id="coupons" class="min-w-full">
  <% if @coupons.any? %>
  <div class="grid grid-cols-4 sm:gap-4">
    <% @coupons.each do |coupon| %>
      <%= render "coupon", coupon: coupon%>
    <% end %>
    </div>
  <% else %>
    <p class="text-center my-10 dark:text-white">No coupons created.</p>
  <% end %>
</div>

app/views/coupons/new.html.erb
<%= render "layouts/top", content_title: "New Coupon", title: "New Coupon", button_text: "Back To Coupons", button_path: coupons_path%>
  <%= render "form", coupon: @coupon, businesses: @businesses %>